name: cat_app
description: Simple cat application which helps you find cats and their photos.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1
  cupertino_icons: ^1.0.5
  http: ^0.13.6
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true